import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Edit, Plus, Trash2 } from 'lucide-react';
import { toast } from 'react-toastify';
import { autoAlertBackend } from '@/api/AutoAlertBackend';
import { useCurrentUserInfoStore } from '@/store/currentUserInfoStore';
import { Button } from '@/components/ui/button'; import { Card } from '@/components/ui/card'; import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

type Alert = { id: string; serviceId: string; dueDate: string; amount: number; status: 'Pendiente' | 'Pagado' | 'Vencido' };
type Service = { id: string; name: string; storeName: string | null };
const empty = { serviceId: '', dueDate: '', amount: '', status: 'Pendiente' as Alert['status'] };
const money = (value: number) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value);

export function Alerts() {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Alert | null>(null); const [form, setForm] = useState(empty);
  const userInfo = useCurrentUserInfoStore((state) => state.userInfo);
  const isAdministrator = ['admin', 'administrador'].includes(userInfo?.user.role.toLocaleLowerCase('es-CO') ?? '');
  const alerts = useQuery({ queryKey: ['alerts'], queryFn: async () => (await autoAlertBackend.get<Alert[]>('/alerts')).data });
  const services = useQuery({ queryKey: ['services', 'alerts'], queryFn: async () => (await autoAlertBackend.get<{ services: Service[] }>('/services', { params: { page: 1, pageSize: 100 } })).data.services });
  const refresh = () => client.invalidateQueries({ queryKey: ['alerts'] });
  const create = useMutation({ mutationFn: () => autoAlertBackend.post('/alerts', { ...form, amount: Number(form.amount) }), onSuccess: () => { refresh(); toast.success('Alerta creada'); close(); }, onError: () => toast.error('No fue posible crear la alerta') });
  const update = useMutation({ mutationFn: () => autoAlertBackend.put(`/alerts/${editing!.id}`, { id: editing!.id, ...form, amount: Number(form.amount) }), onSuccess: () => { refresh(); toast.success('Alerta actualizada'); close(); }, onError: () => toast.error('No fue posible actualizar la alerta') });
  const remove = useMutation({ mutationFn: (id: string) => autoAlertBackend.delete(`/alerts/${id}`), onSuccess: () => { refresh(); toast.success('Alerta eliminada'); }, onError: () => toast.error('No fue posible eliminar la alerta') });
  const updateStatus = useMutation({ mutationFn: ({ id, status }: { id: string; status: Alert['status'] }) => autoAlertBackend.patch(`/alerts/${id}/status`, { status }), onSuccess: refresh, onError: () => toast.error('No fue posible actualizar el estado') });
  const close = () => { setOpen(false); setEditing(null); setForm(empty); };
  const edit = (alert: Alert) => { setEditing(alert); setForm({ serviceId: alert.serviceId, dueDate: alert.dueDate.slice(0, 10), amount: String(alert.amount), status: alert.status }); setOpen(true); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (!form.serviceId || !form.dueDate || Number(form.amount) <= 0) return toast.error('Completa servicio, fecha y monto'); editing ? update.mutate() : create.mutate(); };
  const serviceLabel = (id: string) => { const service = services.data?.find(item => item.id === id); return service ? `${service.name} · ${service.storeName ?? ''}` : 'Servicio no disponible'; };
  const pending = create.isPending || update.isPending;
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h2 className="text-gray-900">Alertas de pago</h2><p className="text-gray-500">Cada alerta registra un cobro. Las notificaciones se crean por separado.</p></div>{isAdministrator && <Button onClick={() => { setForm(empty); setEditing(null); setOpen(true); }}><Plus className="w-4 h-4 mr-2" />Nueva alerta</Button>}</div>
    <Card className="p-5 overflow-x-auto"><table className="w-full"><thead><tr className="border-b">{['Servicio', 'Vencimiento', 'Monto', 'Estado', ...(isAdministrator ? ['Acciones'] : [])].map(label => <th key={label} className="p-3 text-left text-gray-600">{label}</th>)}</tr></thead><tbody>{alerts.isLoading ? <tr><td colSpan={5} className="p-8 text-center">Cargando alertas...</td></tr> : (alerts.data ?? []).length === 0 ? <tr><td colSpan={5} className="p-8 text-center text-gray-500">No hay alertas registradas.</td></tr> : alerts.data?.map(alert => <tr key={alert.id} className="border-b"><td className="p-3">{serviceLabel(alert.serviceId)}</td><td className="p-3">{new Date(`${alert.dueDate.slice(0, 10)}T00:00:00`).toLocaleDateString('es-CO')}</td><td className="p-3">{money(alert.amount)}</td><td className="p-3">{isAdministrator ? <span className={alert.status === 'Pagado' ? 'text-green-700' : alert.status === 'Vencido' ? 'text-red-700' : 'text-amber-700'}>{alert.status}</span> : <Select value={alert.status} onValueChange={(status) => updateStatus.mutate({ id: alert.id, status: status as Alert['status'] })} disabled={updateStatus.isPending}><SelectTrigger className="w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Pendiente">Pendiente</SelectItem><SelectItem value="Pagado">Pagado</SelectItem><SelectItem value="Vencido">Vencido</SelectItem></SelectContent></Select>}</td>{isAdministrator && <td className="p-3"><Button variant="ghost" size="icon" title="Editar" onClick={() => edit(alert)}><Edit className="w-4 h-4" /></Button><Button variant="ghost" size="icon" title="Eliminar" onClick={() => window.confirm('¿Eliminar esta alerta?') && remove.mutate(alert.id)}><Trash2 className="w-4 h-4 text-red-600" /></Button></td>}</tr>)}</tbody></table></Card>
    <Dialog open={open} onOpenChange={value => !value && close()}><DialogContent onPointerDownOutside={(event) => event.preventDefault()}><DialogHeader><DialogTitle>{editing ? 'Editar alerta' : 'Nueva alerta'}</DialogTitle><DialogDescription>{editing ? 'Actualiza el cobro registrado.' : 'Crear esta alerta no envía notificaciones.'}</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={submit}><div><Label>Servicio *</Label><Select value={form.serviceId} onValueChange={value => setForm({ ...form, serviceId: value })}><SelectTrigger><SelectValue placeholder="Selecciona un servicio" /></SelectTrigger><SelectContent>{services.data?.map(service => <SelectItem key={service.id} value={service.id}>{service.name} · {service.storeName}</SelectItem>)}</SelectContent></Select></div><div><Label>Fecha de vencimiento *</Label><Input type="date" value={form.dueDate} onChange={event => setForm({ ...form, dueDate: event.target.value })} /></div><div><Label>Monto a pagar *</Label><Input type="number" min="0" step="0.01" value={form.amount} onChange={event => setForm({ ...form, amount: event.target.value })} /></div><div><Label>Estado *</Label><Select value={form.status} onValueChange={value => setForm({ ...form, status: value as Alert['status'] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Pendiente">Pendiente</SelectItem><SelectItem value="Pagado">Pagado</SelectItem><SelectItem value="Vencido">Vencido</SelectItem></SelectContent></Select></div><div className="flex gap-2"><Button type="button" variant="outline" className="flex-1" onClick={close}>Cancelar</Button><Button type="submit" className="flex-1" disabled={pending}>{pending ? 'Guardando...' : 'Guardar alerta'}</Button></div></form></DialogContent></Dialog></div>;
}
